version: '3'
services:
  db:
    image: mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  web1:
    image: "ruby"
    ports:
      - "3001:3000"
    links:
      - db

  web2:
    image: "nginx"
    ports:
      - "8000:80"
  